### ISSUE TITLE
Licence issues & ambiguity

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1017]
I see a few licencing issues that I believe are important and should be brought up:  
- Enigma is licenced under the GPLv3 according to the headers in the source code but no LICENCE file is present in the repository.  
- I question whether GPL is the right choice here, as to my understanding it prevents a person from distributing proprietary games made with the engine, the issue here isn't that I want to encourage proprietary software but that I question whether this was both @JoshDreamland 's intention when licencing and whether it is strategically advantageous, similar to the reason why LGPL was used for GLibC (competition with products that allow proprietary usage may cause people to turn to the proprietary alternative).  
- Many of the copyright years haven't been updated and have had many commits made long after the copyright date (some still state 2008!)    
  
This is the thread that caused me to raise this issue: http://enigma-dev.org/forums/index.php?topic=2722.new#new

**Comment by JoshDreamland** [comment]
Without a doubt, license hygiene isn't great, on this product. People just don't remember to update them. I'm not sure what happened to our LICENSE file. There was a time in ENIGMA's history where we were distributing GPL2 as the LICENSE, even though the code said GPL3.

Anyway. I chose GPL because it was safe for ENIGMA, as a project. GPL prevents ENIGMA from being stomped out or stolen and commercialized. There's been endless discussion about creating a linking exception or choosing a different license, but nothing has ever come of it. I am reluctant to put code for this project under, eg, Apache 2, or any of the BSD or MIT licenses. Doing so allows far more than creation of proprietary games (which we *do* want to allow).

The basic feeling I leave these discussions with is that I'd rather keep the burden for "doing the right thing" on this team, than trusting the rest of the world.

**Comment by faissaloo** [comment]
>There's been endless discussion about creating a linking exception or choosing a different license, but nothing has ever come of it.  

I think it's about time this stuff was sorted tbh, since it's a barrier to entry for some people and may be allowing people to get away with licence violations out of ambiguity.  
  
>I am reluctant to put code for this project under, eg, Apache 2, or any of the BSD or MIT licenses. Doing so allows far more than creation of proprietary games (which we do want to allow).  
  
In that case I think it's better to go with the LGPL then, since it retains the 'giving back' properties of the GPL while also allowing it to be useful for people who wish to make non-GPL software. I think switching to permissive licenses is a step too far since it would allow a company to take the source code, give nothing back, smear proprietary all over it and then present that to the users.

**Comment by RobertBColton** [comment]
I left a reply on the forum too:
http://enigma-dev.org/forums/index.php?topic=2722

I kind of want these debates to stick to the forum, but I don't want to be rude to you either faisaloo. We've just discussed this a lot before and haven't been able to decide. It's an annoying issue because everyone has a different opinion about what license to use. However!

We do not need to relicense the compiler or LateralGM - ever. The only issue at hand is the engine which is linked into everyone's game, which is all under enigma-dev/ENIGMAsystem. I think people would just stop complaining as much about it if we picked a license. Maybe @faissaloo is right @JoshDreamland and we should just pick LGPL and forget about it. Qt framework uses LGPL and the world keeps turning. I am at the point that @JoshDreamland should just pick his favorite one and let's go with it.

**Comment by RodrigoCard** [comment]
Well, I just need some clarification,[ this page](http://enigma-dev.org/docs/Wiki/License) says
`"A special exemption is provided by our license to allow the commercial selling of software made with ENIGMA. "`
But it is too vague, GPL already allows commercial usage, but an uninitiated person may read this and understand that you can distribute games made with enigma without the source code.
What does that exactly mean?

---
That said, my considerations, I've been fiddling with Enigma in my spare time because I plan to port some open source GameMaker games to some platforms unsupported by yoyo, (an ARM linux device), and learn mode about open source project collaboration. So, for me, GPL is completely fine, these games are open source already :)

But, lets say someone make a commercial game using Enigma, he/she may or may not want to release the game's code, right?
Okay, the game is made, source or no source, huge success on Steam, the author got a chance to release the game in a big closed platform, the Playstation 4 or the Nintendo 3DS, a platform that explicitly forbids source distribution. So even an LGPL license wont work in these cases. So what? :(

---
I am very pro-open source, but sometimes it is not our choice, unfortunately.
You want the project to grow and be more used with less restrictions, but you are all correct to protect enigma.

In my newbie-outsider opinion, A good compromise would be separate the license of the Compiler/IDE and the Engine.
**A copyleft license for the IDE/Compiler and a Permissive license for the engine.**

You could even charge for a closed source commercial license of the engine, but I advise against that because this would cause problems with Yoyo,

---
My 2 cents :)

Any thoughts?

**Comment by fundies** [comment]
Close this and move it to the forum. The tracker isn't for license debates.

**Comment by RobertBColton** [comment]
@RodrigoCard you are right and just about every point you made we already know about. The question is not whether to relicense the engine but what license to give it. Also, the LGPL would not be a problem, you would be able to release your game in binary form. 

Finally, selling the engine would not be a problem with YoYo. Reverse engineering is 100% legal for the purposes of porting software to other platforms. Usually a Chinese wall is used when professional reverse engineering takes place (companies do it all the time). In this case we do that because we only make the functions match the expected functionality of GM's manual.

https://en.wikipedia.org/wiki/Chinese_wall#Reverse_engineering
https://www.eff.org/issues/coders/reverse-engineering-faq

Everyone feel free to continue debating which license ENIGMA's engine should have on the forums. When everyone finally decides on the license we can and will change it.

**Comment by RodrigoCard** [comment]
Thanks for the clarification!
But I want to ask a question about the LGPL itself, not the enigma license, thus, I am asking the question here, since you said LGPL wouldnt be a problem, ok?:

**Is LGPL Incompatible with a closed platform? (Playstations, Xboxes, Nintendos)**
They dont allow freely distributed sources of code for their platforms.

**If so, this license would effectively prevent ports for these platforms.**

**Comment by RobertBColton** [comment]
It should be yes, Mac/iOS/Apple stuff would be the only place it might not. But we will likely not use LGPL as it is not fitting for a game engine. I encourage you to research other licenses as well as zlib, BSD, and MIT.

**Comment by JoshDreamland** [comment]
The LGPL is a terrible fit for this project. It would not allow users to distribute their games, because ENIGMA links your code directly with (L)GPL code. It would also allow anyone who wanted to sell proprietary clones of ENIGMA to do so, as long as all needed pieces of ENIGMA were in libraries. So their fixes would be closed-source and link against an open-source (and still-broken) copy of ENIGMA. That's what we're avoiding: proprietary fixes (or even just rebrands) being marketed, closed-source.
