### ISSUE TITLE
variable_global_get not implemented

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1057]
It seems `variable_global_get` is not implemented yet. I'm reporting in case this is a bug, as [it isn't listed in the wiki page](https://enigma-dev.org/docs/Wiki/Category:Function:Unimplemented) (nor as a [deprecated function](https://enigma-dev.org/docs/Wiki/Deprecated_GML)).

**Comment by 9Morello** [comment]
It seems this function was removed in GM:Studio 1.x and was added again in 2.0 (along with a few others, such as `variable_local_exists`, `variable_global_exists`, etc.). I guess thats probably the reason it isn't implemented yet.

Does anyone know any function to active similar functionality?

**Comment by JoshDreamland** [comment]
I suggest using a `ds_map`; I was opposed to the support of any of the `variable_` functions for a long time; Polygone is the only reason any were added.

**Comment by JoshDreamland** [comment]
I'm closing this issue as part of a sort of "bug bankruptcy" we're running, right now. We're aware that this method is missing, and we may eventually add it, but only because it would be easy to add after more important reflection-oriented features from our roadmap are added (such as `game_save`).

As I hinted earlier, I usually see these methods used as an alternative to a `ds_map` because the data structure functions are less discoverable somehow. I've never seen a legitimate use of this function. That said, this is a really low-priority feature; keeping this bug open isn't helping anything.

**Comment by 9Morello** [comment]
Just a heads up: these functions got added back to Game Maker:Studio 1.4 since a recent update that backported various bug fixes from Game Maker Studio 2. They're called `variable_instance_set` and `variable_instance_get` now. More info [here](https://yal.cc/gamemaker-get-set-variable-value-by-name/).
