### ISSUE TITLE
ERROR: Expected closing triangle bracket

### ISSUE THREAD

**Issue by KelvinShadewing** [enigma-dev/enigma-dev#1109]
This is the GML code I'm using:

    switch(state){
        case standing:
            wait -= 1;
            image_speed = 0.25;
            if(wait <= 0){
                if(holding) sprite_index = sprWaitH;
                else sprite_index = sprWait;
            } else {
                if(holding) sprite_index = sprStandH;
                else sprite_index = sprStand;
            };
            if(attacking) sprite_index = sprStand;
            break;
            //Other cases redacted for brevity
    };

On the sixth line, right before `if`, the compiler says it expects a closing triangle bracket before a closing parenthesis. Running this code in GM8 gives no errors at all. Why would it expect a closing triangle? I've used them before and nothing happened. I even tried changing it to `if(wait < 1)` since I'd used < without = before, but that gives me the same error here. It only happens in this one case, even though the same operator has been used in plenty of other places.

**Comment by JoshDreamland** [comment]
It's possible that `wait` is a template name. Does `1 >= wait` work? Renaming the variable should also work.

**Comment by KelvinShadewing** [comment]
I think it was a template name. When I changed all references of `wait` to `waiting`,  it worked.

**Comment by RobertBColton** [comment]
Yeah that makes this a duplicate of #915 then. At some point we need to come up with a way of blacklisting all keywords outside of `namespace enigma_user`. I think when I added the part that scopes JDI to `enigma_user` it made this problem less noticeable but there are some vestigial leftovers because people are, again, still including STL and stuff where they shouldn't be in the engine.
