### ISSUE TITLE
Renaming MinGW to something like 'Windows Cross Compile'

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1151]
This would follow the convention we're using for Android.ey, AndroidSym.ey and AppleCross64.ey, I believe this is more user friendly.

**Comment by RobertBColton** [comment]
Do you mean for Linux or Windows? That would be really confusing to do because we don't even support MSVC yet, so MinGW is basically synonymous with our plain old "Windows" target at this point even when you are not cross-compiling.

Further we want to hopefully delete the Portable ZIP and replace it with a simple MSYS2 installation, later adding MSVC support. When that time comes MinGW will maybe be used more so for cross-compiling, and more Windows users will likely just use MSVC. But I don't see any real reason to change the names of the compilers in the UI. I think it just sounds confusing unless I don't understand this proposal, in which case, please clarify.

**Comment by faissaloo** [comment]
I meant when running on Linux (Linux/MinGW64.ey and Linux/MinGW32.ey), since there's two different compiler configs for when you're running ENIGMA on Windows natively (Windows/gcc.ey).

**Comment by RobertBColton** [comment]
Hrm, yeah I suppose in that case we could, since that's really the only reason you would compile with Minimalist GNU for **_Windows_** on Linux. Again, I don't know how much it might help, it seems kind of obvious this is the intention of MinGW, so I don't know if people would be confused without changing the name.

I don't have a particular preference on this, maybe @JoshDreamland or @fundies could highlight anything not immediately obvious about this. I would maybe propose something like "MinGW (Windows cross compile)" for the name instead, because hypothetically we could also make a cross-compiler with Clang. ENIGMA currently does work with Clang too, see Travis:
https://travis-ci.org/enigma-dev/enigma-dev/jobs/327955407#L468

That way if we did have multiple cross compilers, the names would not clash, which would be even more confusing. Feel free to send the pull request if you like.

**Comment by fundies** [comment]
There's no need to rename the files but if you want to change the name field inside the ey to something like MinGW 64bit Cross or whatever thats' fine.

**Comment by RobertBColton** [comment]
Another thing to mention is that wclang is the clang cross compiler for Windows. It's the `W` in all of these that make it obvious.
https://github.com/tpoechtrager/wclang

However, I should mention that if I wasn't so familiar with this project and a regular user coming from GameMaker, maybe two years ago, I would also be confused of the differences between GCC and MinGW. Perhaps I can later add a guide to the Wiki explaining how to pick a compiler target. We could also maybe expand the UI a bit to include a brief 1-line description of each compiler target, kind of like extensions have.

Eventually though, our big picture goal is to make cross-compilation much easier. @fundies has even stopped supporting his own cross-compiler patch. What we have been looking into for a few weeks now is getting continuous integration to automatically build games, and we're still in the middle of that. So, I'm going to hold off on doing anything about this one for right now.

**Comment by fundies** [comment]
No point in keeping this open. If you really think the names of the ey need to be changed you can make a pull request.
