### ISSUE TITLE
Suggestion: integration with GMEdit

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1178]
For those who aren't aware, [GMEdit](https://github.com/GameMakerDiscord/GMEdit/) is a FOSS code editor for Game Maker: Studio developed by YellowAfterlife, which _drastically_ improves workflow for anything below Game Maker Studio 2. You can easily use the editor for all scripts and objects and use the IDE only for adding resources to the project (sprites, backgrounds, etc.).

I always had the impression most of ENIGMA issues came from LateralGM crashing. Plus, the code editor in GMEdit is just much better compared to LateralGM's or GM:Studio 1.4's. It feels a lot like Sublime Text, except you can't really use Sublime with GM projects because of XML stuff staying in your way. GMEditor takes care of that.

One thing that makes it harder to use GMEdit with ENIGMA is [this issue](https://github.com/IsmAvatar/LateralGM/issues/341). I don't know how trivial/hard is to add this option.

**Comment by fundies** [comment]
We have our own c++ ide in the works but it's in ivery early development. I think it'll be usable in a few months if @RobertBColton stops obsessing over fixing light switches to impress his landlord

**Comment by RobertBColton** [comment]
@9Morello I am actually much more open to this suggestion than working on the LGM one, even though I am actually going to close this.

We are already working on a new IDE here, and have a new IPC mechanism for the compiler using protocol buffers. @fundies has it already loading GMX projects. We plan on having the IDE lazy load resources and listen for file changes on the disk, so don't worry, we already have this specific feature you want planned.

Now specifically in regards to GMEdit, I've actually already seen this and am aware of YAL's projects. Before I seen his though, I was also poking around with Electron myself because I became very familiar with Vue.js after I created ActionMaker:
https://enigma-dev.org/forums/index.php?topic=2806.0

That said, there is nothing stopping anybody from using GMEdit in combination with ENIGMA. If GMEdit supports user extensions, then it would be no different having an ENIGMA plugin for GMEdit than it is having one for LGM. ENIGMA can be used with anything is basically what I am saying. The fact that @fundies has our new IPC backend loading GMX projects also means the CLI, that powers our continuous integration testing, will also soon be able to load GMX projects. And it would be very easy to add ENIGMA to GMEdit using this same CLI, by simply having it pass the file path for ENIGMA to build the game.

So, there really isn't anything here for us to even work on, we already have everything you need to write an ENIGMA plugin for GMEdit, but I would simply wait until we stabilize our new backend a little better. That said, if you have any specific changes you need made in ENIGMA to make it more compatible, let us know. For now, I am going to close this, because the features you request are planned or already exist, and just stay tuned on further announcements from us.

**Comment by 9Morello** [comment]
@fundies @RobertBColton Thanks for the fast answer and clarification. I had no idea a new IDE was in the works, and as such, there's really no reason for anyone to work on [the other issue](https://github.com/IsmAvatar/LateralGM/issues/341). 

Looking forward to this new IDE. I suppose you're writing it to be cross-platform from the start?

**Comment by RobertBColton** [comment]
Absolutely, and yes to that specific question. Believe it or not this is actually not the first time we've experimented with a new IDE. This time is just different because it's more than just rewriting the GUI layouts and stuff (the easy part that anybody is capable of), we have actually created the architecture for a data model layer that makes the IDE super simple to create. Again, this data model layer is using the protocol buffers format we have wrote for the compiler.

Because Google's protocol buffers can also be used for inter-process communication we can also put the IDE in a separate process from the compiler, which has all sorts of advantages, including safety/stability. I don't want to share any more details right now, but I am hoping to have a prototype to announce on the forums sometime before summer. I will discuss the architecture in more detail and also document some steps to creating a new editor. Just stay tuned for more!
