### ISSUE TITLE
Suggestion: Implement Data Structure Accessors & Compatibility Setting

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1214]
I don't think ENIGMA supports [these](https://www.yoyogames.com/blog/35/accessors-for-data-structures-and-arrays) yet.

**Comment by RobertBColton** [comment]
It does not, and believe or not it might never support them in the same way (I personally don't like them either):
https://github.com/enigma-dev/enigma-dev/issues/988#issuecomment-237962836

That said, we do plan on *real* accessors, as in just overloading the subscript `[]` operator for ds functions. It would just be the subscript operator but without any special symbol. However, we could make it an option where the symbol is not a syntax error for GMS compatibility.

Seeing as we don't actually have a ticket for this yet, although we plan to do it, I can leave this open for when we do happen to get around to it.

**Comment by 9Morello** [comment]
@RobertBColton Good to hear, I'd rather not have to use the symbols either. Though I agree with you an option to enable them for compatibility reasons is a good idea.
Thanks for your attention.

**Comment by RobertBColton** [comment]
Absolutely, and also, I'm not actually sure the reasoning for the special symbols unless it's some limitation of their use of Clang. As you know, we don't use Clang, we use our own custom JDI written by Josh, so whatever API limitation Clang has we can just work around it. I'm saying it may have just been out of YoYoGames hands, or they didn't feel like trying to modify Clang directly.

**Comment by JoshDreamland** [comment]
The idea is to solve this with proper typing (at least in the sense that C++ typing is proper, for my [fedora enthusiasts](https://en.wikipedia.org/wiki/Haskell_(programming_language))) rather than symbols to tell the interpreter that you really hope the object you're accessing has this type.

A while back, ENIGMA supported C++ template types. Polygone broke them as a duct-tape solution for a problem with instance variable access. You used to be able to declare `map my_map;` and then set `my_map["key"] = value;`, just like that. Unspecified template parameters were assumed to be `variant`. That hasn't worked in a long time, and won't be fixed until I get back into developing the compiler.

Regardless, I stand by my statement that these key hacks will never be supported.

**Comment by 9Morello** [comment]
@JoshDreamland From your post, it seems that the syntax you explained (`map my_map; my_map["key"] = value;`) would be supported sometime in the future.

That being the case, is it possible to remove these special symbols during pre-compiling and maintain compatibility?

Thanks for the attention, all of you. Looking forward to the new IDE.

**Comment by JoshDreamland** [comment]
It falls within the realm of possibility, yes, but it doesn't make the problem any simpler. It's also not as simple as removing the symbols, because we seek to statically define types. If we wanted, we could just replace the symbols with a cast to a custom key type and add an overload to var's `[]` for those types. The overload would just defer the call to the correct `ds_` calls (which are all extensions). It would be a rat's nest of backward hacks to support a syntax which is itself a backward hack.

**Comment by 9Morello** [comment]
@JoshDreamland FYI, based on the errors I got with my game, it seems that what GMS does is replace ` variable = my_map[? "key"];"` with `variable = ds_map_find_value(my_map, "key");`. In the error message, it shows the `ds_map_find_value` function as being part of the code.

**Comment by JoshDreamland** [comment]
Unsurprising; we'd end up doing similar (the var overload would just call the correct function, rather than being a text replacement).
