### ISSUE TITLE
Moving to C++17?

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#1308]
I think it would be a good idea to start using C++17 soon, there's janky stuff like this because we're on C++11:
https://github.com/enigma-dev/enigma-dev/blob/277d3e583005792766cb1320116836a6445f7453/ENIGMAsystem/SHELL/Universal_System/make_unique.h
I'd also really like to take advantage of the fact they put constexpr on steroids, for example: recently there was a commit with a map of colours to names for which we could completely eliminate runtime cost with something like: https://github.com/serge-sans-paille/frozen

**Comment by RemoveRusky** [comment]
jdi still doesnt even support c++11 and travis-ci is on gcc 4.8 still. so not likely

**Comment by faissaloo** [comment]
You're right, JDI completely slipped my mind.

**Comment by RobertBColton** [comment]
I see they did that recently in the engine. There's also janky stuff like this we did somewhat recent:
https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Mock_JDI_Headers/string

We can take a deeper look at JDI once we get all of the important stuff out of the way. Me and fundies are trying to focus on some particular things and I'll be back on the new IDE pretty soon. Our first and primary goal right now is cleaning up a lot of garbage (pretty much done) and expanding to Android without breaking anything. Again, we are so lucky for our CI now, ENIGMA has never been this good.

As far as emake goes though, I use C++14 exactly in libEGM's GMK reader for make_unique. I am going to use it for all of the readers too because Josh wants `load_project` to return a unique_ptr.
https://github.com/enigma-dev/enigma-dev/blob/ff074e643b6e47cf3b2d73e6260834361c169d75/CommandLine/libEGM/Makefile#L13

Regardless, there is still such a thing as "too new" when it comes to the engine. Other than the minor workarounds we have temporarily, is there something specific from C++17 you want?

**Comment by faissaloo** [comment]
The engine currently makes excessive use of macros, C++17 gives us things like inline variables and if constexpr which will make debugging a lot less of a pain, this is my main reason for wanting C++17, so we can go through and clean out most macros and replace them with solutions that in some cases may be more efficient as they can be definitively resolved at compile time. C++14 also gave us [[deprecated]] which would find ample use in the engine as well as binary literals which would help clarify stuff like thing&0x80 (like in the JSON extension) etc.

**Comment by RobertBColton** [comment]
Alright, fair enough, neither of us (me/fundies) have been too happy about the abundant macros either for these reasons too. We'll see, this is going on the backburner, I am right now in Discord trying to get Android going with fundies. I'm on samplers right now and I have to send it to master. Android is my top priority at the moment.
