### ISSUE TITLE
Building ENIGMA from source on Windows currently fails

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1330]
I'm trying to follow the instructions [here](https://enigma-dev.org/docs/Wiki/Install:Windows) to build ENIGMA and emake. I cloned the repo, entered the directory and tried to run `make`, and got the following error:

```
make[1]: Entering directory '/home/Imouto/enigma-dev/CommandLine/protos'
which: no grpc_cpp_plugin in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/)
make codegen
make[2]: Entering directory '/home/Imouto/enigma-dev/CommandLine/protos'
which: no grpc_cpp_plugin in (/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/)
mkdir -p codegen/
protoc -I=. -I=/usr/include --cpp_out=codegen/ project.proto
make[2]: protoc: Command not found
make[2]: *** [Makefile:37: codegen//project.pb.cc] Error 127
make[2]: Leaving directory '/home/Imouto/enigma-dev/CommandLine/protos'
make[1]: *** [Makefile:49: lib] Error 2
make[1]: Leaving directory '/home/Imouto/enigma-dev/CommandLine/protos'
make: *** [Makefile:28: libProtocols] Error 2
```
Additionally, the Pacman command on the wiki page doesn't install GCC.

**Comment by RobertBColton** [comment]
You need one more package that we just recently added for the protocol buffers.
`pacman -S mingw-w64-x86_64-protobuf`
When I first wrote the wiki page, protobuf was not _yet_ a requirement because we had that in another branch. I've now updated that Wiki page:
https://enigma-dev.org/docs/wiki/index.php?title=Install%3AWindows&action=historysubmit&diff=31807&oldid=31713
Going forward, our AppVeyor and Travis yml files should serve as great references for everything that one needs to setup ENIGMA if we forget something on the wiki. Although, I'll admit it's overwhelming compared to a wiki guide if you aren't familiar with it.
https://github.com/enigma-dev/enigma-dev/blob/ee0e1f887fb5dae203ce7970cc0ae14ed113f196/appveyor.yml#L58
Additionally, the following YouTube video we've uploaded may help you if you get stuck again further. It shows setting up the new installation in a Windows 10 Virtual Machine.
https://www.youtube.com/watch?v=tAejbYc3LRI

>Additionally, the Pacman command on the wiki page doesn't install GCC.
Finally, I must correct you here, you don't actually install GCC manually, it comes with MSYS2 when you do the initial setup. You need to make sure you follow all 8 steps on the MSYS2 setup page: http://www.msys2.org/

Hope that helps, and let us know how it goes. If you get stuck again, stop by the Discord channel because fundies, TKG, and some other forum members are always there, and they've all managed to get this new installation going.

**Comment by 9Morello** [comment]
@RobertBColton Thanks for the instructions. It seems I forgot to update MSYS2 right after installing. Maybe that's why I didn't have GCC.

Installing the dependencies you linked (and reinstalling Java because I got the wrong version first (y)) solved the issue.

It might be a good idea to update the instructions on how to run LateralGM for the command line. I thought MSYS2 was aware of it, when in fact you have to type the correct folder (as shown in the video).

**Comment by RobertBColton** [comment]
Good then, so what are your thoughts on the new setup method? I would like to see an installer down the road as well as a separate MSVC setup for ENIGMA (using NuGet for depends), but if you'll put that aside for a second. It's a bit bigger, but in a way it's better organized because you are installing the dependencies consistently (through Pacman) as opposed to us just hacking everything together into a ZIP file. The setup for Windows now is a lot more like it is for Linux. I think people are actually having an easier time with it, especially once they get used to it, but I can't tell yet.

**Comment by 9Morello** [comment]
It's ok for now, specially with the recent development speed up. There's nothing to complain, really. It's working.

Some time in the future though, it would be nice to have a stable release with a bundle installer. Does ENIGMA currently have a roadmap?

**Comment by RobertBColton** [comment]
Fair enough, and no there is no roadmap other than the mental one we have in our heads. We've been discussing it more over Discord but my focus has been on cleaning up graphics and helping fundies do certain aspects of that which relate to OpenGL ES.

I don't know if you see it on your end but we keep editing this in a branch and we have OpenGL ES 3 building (I'm working on GLES 2 as we speak). And we just a few days ago got games compiling with Android Studio. We need to cross target GLES 2 also since more mobile hardware supports that. We'll have more details on all of this, and I wasn't too particularly interested in the whole Android thing, just on graphics deduplication, but it's a noble goal and it crosses over with my goals hence why I'm spending time to help fundies with it.

What took quite a while was setting up the graphics tests and getting them just right. All of this is good for ENIGMA in the long run because it makes it easier for people to contribute because there's less code, that's cleaner, and less likely to break (we'll know if and when it does break too). Things are all going swimingly around here lately really. 🤣 We'll have more announcements on all of this soon.

**Comment by 9Morello** [comment]
Yup, I'm aware of it. There was really a ton of commits recently. Didn't know you guys already got them compiling with Android Studio though, that's pretty nice. I also agree with you that the graphics tests will (hopefully) prevent breaking stuff.

I'll keep reporting issues that I find here for the sake of organization, but hopefully I'll get on touch with you guys soon on Discord.

**Comment by RobertBColton** [comment]
Yeah, we're pretty dedicated to this thing now. Imagine we did all of these changes over the past year and there's been some... struggles... but we haven't really broken anybody or anything to the point of unusability. In fact, we brought every system and extension back from the brink of utter destruction haha. When we started with the CI so little was even building, I can't even list all of the systems/extensions we had that simply failed to compile out of the box.

But yeah, that sounds good, and just try to focus on reproducibility of an issue the most as well as grouping related issues together. Best way to do it. 👍
