### ISSUE TITLE
array_create is not implemented

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1331]
[This function](https://docs.yoyogames.com/source/dadiospice/002_reference/001_gml%20language%20overview/array_create.html) seems to not be implemented yet.

**Comment by RobertBColton** [comment]
Sigh, it's true, this function is not implemented. I'll ask @JoshDreamland if he'll let me implement it, I should be able to do it, and it's only useful over the traditional GML syntax because it allows you to initialize it to a value.

Anyway, I secretly think this function is hilarious because they added simply because they don't want to support an initialization syntax like C++ has. In C++ you do the following if you want to initialize an array of 5 values to some number.
```cpp
int myarray[5] = { 999 };
```

But yeah, I'll ask Josh, this is actually an easy one I think.

**Comment by RobertBColton** [comment]
Closing as resolved by #1335 where I added the function along with the other missing array functions.

Also, I was wrong about C++, the syntax I showed:
```cpp
int myarray[5] = { 999 };
```
Actually sets the first element to 999, and the rest as 0. C++ doesn't have a built-in way to do it either. So this is overall a good API change. This syntax does still work in ENIGMA if one disables automatic semicolons. Cheers!
