### ISSUE TITLE
gamepad_is_connected isn't implemented

### ISSUE THREAD

**Issue by 9Morello** [enigma-dev/enigma-dev#1398]
It seems the function `gamepad_is_connected` isn't implemented, Its functionality is explained [here](https://docs.yoyogames.com/source/dadiospice/002_reference/mouse,%20keyboard%20and%20other%20controls/gamepad%20input/gamepad_is_connected.html).

**Comment by RobertBColton** [comment]
This one is kind of funny, but yes it's still an issue. I actually already rewrote and fixed the gamepads once in #966 but we never merged it. That's why all these gamepad issues are still open. I've been meaning to extract that file out of that pr for a while now but just haven't gotten to it. I was planning to do it from scratch though, because even that rewrite has some issues. For now, I suggest that you try out the SDL platform, which works everywhere, because fundies has told me that he implemented joysticks and gamepads for it. If that is the case, then the gamepad should work like GMS.

**Comment by RobertBColton** [comment]
Actually, I am going to have to close this, it seems you forgot to enable the "XInput" Extension in ENIGMA Settings, please do so. The function `gamepad_is_connected` has already been implemented.
https://github.com/enigma-dev/enigma-dev/blob/4e8ad7c3857794f490610c621ae64ae54b3456b0/ENIGMAsystem/SHELL/Universal_System/Extensions/XInput/XIgamepad.cpp#L30

**Comment by 9Morello** [comment]
Thanks for the speedy reply.
Indeed, enabling XInput in the Settings solved the problem. Maybe it's a good idea to have it enable by default, since GM supports it out of the box?
After enabling it, I tried to compile the project and it seems `device_mouse_check_button` is missing now. Functionality is described [here](https://docs.yoyogames.com/source/dadiospice/002_reference/mouse,%20keyboard%20and%20other%20controls/device%20input/index.html). Is there anything else I should enable?

For reference, I've been trying to compile [this](https://github.com/GameMakerDiscord/input) (the GMS1 version).
