### ISSUE TITLE
How to make executable for Windows and Mac?

### ISSUE THREAD

**Issue by PyxelPranav** [enigma-dev/enigma-dev#1403]
Help me, quick! I'm in a 48 hour game making competition called Alakajam. I have a Linux PC and I can compile for linux but not not for windows or mac. Can a shared library be opened by a windows PC or a Mac?

**Comment by RobertBColton** [comment]
I don't believe a shared object can be opened by Windows, Windows has dynamic link libraries (*.dll) where Mac has (*.dylib) files. Regardless, it wouldn't matter even if Windows could open shared object files because the compiled executable code will be different anyway between Windows and Linux. I can answer other questions for you and am also willing to compile your game for you on Windows, that's about the best I can offer.

Linux uses ELF for executables and Windows uses something else:
https://en.wikipedia.org/wiki/Executable_and_Linkable_Format

**Comment by JoshDreamland** [comment]
You can also build your game using MinGW from Linux. I am not sure where you are getting a shared library that you want to distribute with your game, but you can probably find a Windows build of it.

**Comment by RobertBColton** [comment]
Alright, I hope everything worked out for him in the end. It's been over a week and no reply, so I am going to close this. We did the best we could to answer his questions.
