### ISSUE TITLE
error on startup

### ISSUE THREAD

**Issue by FlameFireling** [enigma-dev/enigma-dev#1427]
`
Operating System: Windows 10
Version: 10.0
Architecture: amd64

Java Name: Java HotSpot(TM) 64-Bit Server VM
Java Vendor: Oracle Corporation
Version: 10.0.2

Available processors (cores): 8
Free memory (bytes): 254597232
Maximum memory (bytes): 1048576000
Total memory available to JVM (bytes): 268435456

File system root: C:\
Total space (bytes): 119455870976
Free space (bytes): 22750498816
Usable space (bytes): 22750498816

File system root: D:\
Total space (bytes): 104853504
Free space (bytes): 83210240
Usable space (bytes): 83210240

File system root: F:\
Total space (bytes): 97192505344
Free space (bytes): 85367668736
Usable space (bytes): 85367668736

File system root: G:\
Total space (bytes): 409740742656
Free space (bytes): 200799563776
Usable space (bytes): 200799563776

File system root: H:\
Total space (bytes): 493163925504
Free space (bytes): 31107862528
Usable space (bytes): 31107862528

Stack trace:
java.lang.NoClassDefFoundError: javax/swing/text/rtf/RTFEditorKitExt
	at org.lateralgm.main.LGM.main(LGM.java:2278)
Caused by: java.lang.ClassNotFoundException: javax.swing.text.rtf.RTFEditorKitExt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 1 more
`

**Comment by RobertBColton** [comment]
Hi, thanks for reporting the issue! Unfortunately, the origin of the error message is not in this repository, it is in the LateralGM codebase. So I will need to close it here.

It seems as though you have obtained an outdated release of LateralGM which is missing a fix for this issue. The issue has not been reported yet on the LateralGM tracker because a fix has already been merged.
https://github.com/IsmAvatar/LateralGM/pull/331

You can obtain a more up to date release of LateralGM from the releases page of that repository.
https://github.com/IsmAvatar/LateralGM/releases

Please understand that LateralGM is not being actively developed and I am working on a replacement for it with RadialGM. Thank you.
