### ISSUE TITLE
Windows game EXE crashes on startup in compile mode

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1437]
on windows, using compile mode, game exe crashes on startup. Only tested with 64-bit exe because of other unrelated bugs preventing me from building 32-bit exe's.

Only crashes on startup using compile mode. Builds and runs just fine in run mode. So while i would distribute my game exe found in the temp folder using run mode, since compile mode is broken, i can't anyway because the run mode exe has a console window it opens with the game when not running from LGM. If it wasn't for that ugly console window, I'd be ready to distribute a final build of my game 64-bit for Windows, but even then I'd be making the exe with run mode instead of compile mode, and compile mode as previously stated just crashes on game startup.

**Comment by RobertBColton** [comment]
This is a real stinker, as you can see in the screenshot I took down below, I am able to launch compiled games from Windows Explorer without any issue. You can see I compiled the game twice, which is because I tested it first with #1440 to see if it would affect Windows too, but clearly it didn't since both seem to work.

So this has to be something specific to your game. You should try reproducing this with an empty game and other games. You could also run GDB on your compiled game that does crash, but the lack of debugging symbols may make it impossible to find anything.

![Compiled AI Tutorial Launched from Explorer](https://user-images.githubusercontent.com/3212801/48659249-18bfb180-ea1c-11e8-91af-b0877566eb44.png)

**Comment by RobertBColton** [comment]
Alright, another update to this, this time I did as I told you I was going to do and build your game in compile mode. I have to say it does work and double clicking the produced executable runs the game just fine. This suggests, since I recently upgraded my MSYS2, that the crash you are experiencing is related to your environment in some way and you should probably try doing an upgrading or a fresh MSYS2 install as I recommended.

![Windows Key to Success Compile Mode](https://user-images.githubusercontent.com/3212801/48688635-0917a880-eb95-11e8-90d2-4efba26dfe01.png)

**Comment by time-killer-games** [comment]
@RobertBColton I updated MSYS2 and ENIGMA and now everything works! Thank you so much!!! :D
