### ISSUE TITLE
Window sizes seem off and cursor disappears while writing code

### ISSUE THREAD

**Issue by PyxelPranav** [enigma-dev/enigma-dev#1482]
I use ENIGMA and LateralGM on a linux machine, every time I create a sprite it's way too big and when I create an object its too wide. I spend so much time resizing them so they can fit on my screen than actually working on my game.

Problem no. 2 - Everytime I try to write code, there is a chance of the cursor disappearing. I can still write code, but it seems impossible to write it fast without a cursor.

I think there is a YouTube video on how to install enigma for linux users, Here is the link - https://www.youtube.com/watch?v=xVEBcwrL1iM

Even the guy in the video has problems with the windows, especially the new sprite window.
The settings in the 'Game Settings' dialogue box are almost impossible to change, because the 'Save' button gets hidden every time.

I use a laptop with a 1366 X 768 resolution, with 8GB RAM but it still feels bulky to use ENIGMA due to the lag and window size problems.

When I tried installing LateralGM without ENIGMA(just the .jar) the window sizes were perfect.

**Comment by RobertBColton** [comment]
Hi, thanks for taking the time to voice your concerns about these issues. I can basically just say that I empathize a lot with your frustrations. But first I must clarify that most of these issues actually belong to LateralGM, whose repo can be found here: https://github.com/ismavatar/lateralgm

You see, when the ENIGMA project started it did not actually have an IDE, and LateralGM was being developed in Java as an alternative IDE for GM5-GM8. The two projects later merged and that's why today LGM is the defacto IDE ENIGMA has right now. However, you may have heard that we're working on replacing it with a [C++ IDE that's tailored for ENIGMA](https://github.com/enigma-dev/RadialGM) and not for GM. It has not reached alpha stage yet but will likely soon, I do not encourage testing or trying to use RGM at this point.

With few developers, I am trying to focus my efforts around the new IDE, thus LGM is currently not being maintained and nobody is actively working on it or trying to improve it much. That all said, I think I can still help to alleviate some of your issues. The first thing that would be useful to know is if you are running LateralGM using OpenJDK or the Oracle JDK? You see, it's well known that Java/Swing applications are [much buggier in OpenJDK](https://github.com/IsmAvatar/LateralGM/issues/227) and it could be the cause of many of your UI issues.

* The cursor issue has to do with JoshEdit which LGM uses as its code editor and I believe I've experienced this at times myself: https://github.com/JoshDreamland/JoshEdit/issues/51
* The Game Settings save button issue I also experience myself, and it would require a bit of refactoring to solve. I believe it's because the dialog is packed to the size of the first tab, instead of the smallest size of all the tabs.

Now, as I said, I am not really too interested in trying to fix LGM issues at the moment. I am actually quite principled against the use of Java to build an IDE for ENIGMA (for very good reasons), hence my efforts to replace LGM. However, I could make time to fix at least one of the issues you are facing if you insist. Finally, I would then appreciate if you could move this ticket to the appropriate repos (since the issues you describe are not in this repo, this is the engine/compiler) I would close this ticket here.

**Comment by PyxelPranav** [comment]
I am totally for this point. Java is slow as hell and probably not the best for making a big IDE for game development. I checked the RadialGM repo and it looks like it has gone a long way. I have never coded a game in native ENIGMA, because I didn't know I could. 

I feel LGM has no future, and especially not for big projects like ENIGMA. Thank you so much for responding with such a big message so quickly. Your commitment to this project will surely make you succeed. God bless you.

Really sorry for the reckless way I started this issue. I was only 5 or 6 levels away from completing my platformer and every developer is quite restless at the last stages of game development. I simply didn't see the full picture.

Honestly, after all that I don't even care about using ENIGMA with LGM, now I'm eagerly waiting for RGM to mature and be usable.

P.S. plz make a linux build for rgm

**Comment by RobertBColton** [comment]
Hey, don't worry about it, I like making sure the users are on the same page as the developers here and I know the community appreciates the detailed feedback I give. My main opposition to Java here is just that it's out of our reach to even make a usable application lol, even on a single platform there's more JDKs than just the OpenJDK and Oracle JDK. Then on top of that each JDK has its own implementation of the Java APIs like Swing. It just makes everything very unpredictable, which obviously is not good for stable software development. On top of that, Oracle as a company has taken some [troublesome actions which have a major impact ](https://www.wired.com/story/the-case-that-never-ends-oracle-wins-latest-round-vs-google/) on the legality of the platform.

But yeah, the focus of ENIGMA has always been modularity. One alternative to using ENIGMA without LGM right now is the new `emake` which is part of the new infrastructure RGM is using. We've made a nice wiki guide explaining it and how to use it to build projects from the command line.
https://enigma-dev.org/docs/Wiki/Command_line_interface

If you happen to find a use for any of the engine or compiler before RGM's first public releases, and you find an issue, feel free to report it here and we will take a look at it. My earlier request is just a matter of me keeping everything organized where it needs to be.

Just stay tuned to the site for more announcements. The project is really improving with the new continuous integration and other development in recent months.

**Comment by PyxelPranav** [comment]
Thanks a ton! Can ENIGMA & emake run on linux? I'm quite confused on how to use it. What I understood from the CLI page you linked me to is that I can make games from the command line because _**" Enigma started out as a CLI exe only. "**_

But you know.. I feel kinda salty with that 'exe'

**Comment by RobertBColton** [comment]
Well, they just mean that `compileEGMf.dll` (Windows), compileEGMf.so (Linux), and compileEGMf.dylib (Mac) was once an executable. Even though Linux doesn't have the exe file extension they are still executable files stored in the Executable and Linkable Format (ELF).
https://en.wikipedia.org/wiki/Executable_and_Linkable_Format

To clarify, `compileEGMf.dll` is just a library which exports ENIGMA's compiler methods to be used by an IDE. In this case, lgmplugin (aka `enigma.jar`) uses Java Native Access (JNA is the successor to JNI) to load `compileEGMf.dll` and add a run button to LGM's toolbar. Then when you run the game, the lgmplugin copies LGM's game data classes into C structures and passes it to `compileEGMf.dll` which then converts the GML to C++ and builds the game executable.

To get emake if you don't already have it, you just need to run `make emake` on the command line. We only mention this on the Windows install page at the moment.
https://enigma-dev.org/docs/Wiki/Install:Windows#Get_ENIGMA

That said, it definitely builds on Linux, because our continuous integration (Travis) actually uses emake to build games and run tests to prevent engine bugs. Just understand that since `emake` is not Java, it has a new set of dependencies in order for `make emake` to succeed. You will need to install pugixml (GMX), rapidjson (YYP), protobuf (Google protocol buffers is emake/RGM's replacement for JNA), and finally yaml-cpp (the new EGM format we're inventing).

If you have any trouble getting emake to compile on Linux, feel free to ask me. It's honestly not very many packages compared to how large Java is, and we are planning static releases of it for Linux alongside RGM. Another useful reference is the `travis.yml` in our project since it basically has to run the same Linux commands to build emake.
https://github.com/enigma-dev/enigma-dev/blob/0b44fbfc4cf3a5c1164147be75aacdb204be89ac/.travis.yml#L17

**Comment by PyxelPranav** [comment]
Thanks for the explanation, my project compiles and I can use Sublime Text to edit the xml files for the objects.

**Comment by RobertBColton** [comment]
That's great! I am glad to hear that as it has mostly only been tested by those of us developing the new stuff. There's a lot of work to be done yet, and the YYP reader I started for libEGM (our new reusable C++ library which loads egm/gmk/gmx/yyp using Google protocol buffers) needs some additional compatibility layers as does the engine for GMS2. Also understand, due to the new organization of ENIGMA, it's possible to reuse our tools as a third party (you could reuse libEGM in your own IDE etc) and we encourage this (because we want people to adopt ENIGMA and its tools). But just stay tuned, some more great things are going to come!
