### ISSUE TITLE
Ubuntu/Debian Linux install broken

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1527]
I deleted my enigma-dev folder for an attempt at fetching a fresh install.

I used the usual script from the Ubuntu/Debian install page for my Ubuntu (bionic beaver):
https://enigma-dev.org/docs/Wiki/Install:Linux

During installation, many errors of the same exact missing header show up in the terminal: 
https://pastebin.com/EhZ3wriY

Then LGM opens with the following:
![screenshot from 2019-02-02 16-38-50](https://user-images.githubusercontent.com/4379204/52169676-6b9b3200-270a-11e9-8953-97ba27521a50.png)

So until that header issue gets resolved, I can't build the *.so file for LGM it appears.

**Comment by RobertBColton** [comment]
As of #1448 (a1aa34d57d91e438bf937a39d902a6556932eaec) we now depend on Google Protocol Buffers. I will make an announcement. Check that same guide again to see how to install it.
https://enigma-dev.org/docs/Wiki/Install:Linux#Source_Code

**Comment by time-killer-games** [comment]
@RobertBColton Ok, I thought it was working because it was taking longer in with LGM's compile form, but it is still failing to build the library.

Here's the new terminal log:
https://pastebin.com/Y2dhxYzr

**Comment by RobertBColton** [comment]
Ok, that's Josh's fault, allow me to explain. Most of those are actually warnings we need to clean up. The real error is this:
```
compiler/compile.cpp:433:56: error: no match for ‘operator[]’ (operand types are ‘const google::protobuf::RepeatedPtrField<buffers::resources::Timeline_Moment>’ and ‘int’)
         wto << "  curr[" << game.timelines[i].moments()[j].step()
                                                        ^
```

It's Josh's fault because he made the change to use the `[]` subscript operator instead of `Get` which isn't in older versions of Protobuf's library. Ubuntu notoriously has outdated protocol buffers, so you need to update your protocol buffers basically... maybe from a PPA. We will probably also send another pull request now to remove the subscript operator and just make it compatible with older protobuf. Sorry about this.

**Comment by time-killer-games** [comment]
fixed
