### ISSUE TITLE
Improve efficiency of room_caption

### ISSUE THREAD

**Issue by forthevin** [enigma-dev/enigma-dev#163]
room_caption is currently commented out of the system, since it used to be implemented very inefficiently. This makes a significant difference for rooms with high room_speed. Implement room_caption again, and ensure that it does not decrease performance significantly at high room_speed's.

**Comment by TheExDeus** [comment]
Yes, caching does happen, so I'm not sure if there is more optimizations to be done here. But there is conflict between room_caption and window_set_caption in user code. If the user sets window_set_caption("FPS:"+string(fps)), but the room_caption is empty (the default), then it will flicker between the two. What would be the best thing to do here? Set room_caption in window_set_caption? So there would be two ways to update it?

**Comment by RobertBColton** [comment]
Just a heads up, GMS removed room caption all together.

**Comment by TheExDeus** [comment]
I also feel that room_caption is not really useful when we have a specific function to change it. I don't have problems removing it, but it is used in several other places as well (room editor for one). Maybe we can leave it for now, so you can get it and set it, but it shouldn't change the window title? This way users can use it to identify rooms by name. For this we would only need to remove window_set_title from screen_refresh() function in Bridges.

**Comment by RobertBColton** [comment]
I am not sure, I wouldn't do it just yet because, as soon as you do, it's going to be incompatible with a lot of old games. Especially the simple Mark Overmar's examples, like Game of Life I think is one, which make use of the caption for score and stuff. LGM doesn't have the global caption title setting yet either. I'd hold off on it for now and just go with caching the thing like you guys were talking about.

I'm just digging stuff up on the internet for you to try first. Some Delphi programmers noticed how slow SetWindowText is, and also regular C++ programmers have commented on this. Apparently you can get a faster version by not letting Win32 do the string manipulation.
http://www.micro-isv.asia/2008/10/dont-get-hung-up-on-milliseconds/
http://stackoverflow.com/questions/16627530/setwindowtext-slow-win32-c

```cpp
SetWindowText(enigma::hWnd,(char*) caption.c_str()); // instead of this
SetWindowTextA(enigma::hWnd,(char*) caption.c_str()); // try this

// also try this
std::wstring wstr;
wstr.assign(str.begin(), str.end());
SetWindowTextW(enigma::hWnd,(LPCWSTR)wstr.c_str());
```
Benchmark the performance difference between these three versions and see what you come up with.

**Comment by rpjohnst** [comment]
`SetWindowText` is just a macro for `SetWindowTextA` or `SetWindowTextW`, and `SetWindowTextA` probably does the exact same conversion internally that you're trying to do with `std::wstring` (which btw is not guaranteed to be the same layout as `LPCWSTR`). So in the end, it's not going to make a significant difference which one you use (unless, like those articles, you're doing something completely insane, like calling `SetWindowText` by itself in a loop).

I suggest leaving it as-is and focusing on the real issue of the conflict between `room_caption` and `set_window_caption`. If you end up noticing a slow-down and you legitimately track it back to calling `SetWindowText` once per frame, I will die of shock and then you can think about caching strings or switching them to UTF-16 or something.

**Comment by RobertBColton** [comment]
I am testing on my old ENIGMA revision, and apparently window_set_caption is constantly overridden by room_caption, and the behavior is the same in GM8.1.

Put this in the step event of a single object in both ENIGMA and GM8.1
```cpp
window_set_caption("test" + string(random(10)));
```

I guess the purpose of window_set_caption is to set the immediate window caption when loading a game, which I have no problem with. So this seems like caching room_caption is a perfectly acceptable solution.

**Comment by TheExDeus** [comment]
I don't really think there is a slowdown, as we cache room_caption for two years already. So currently I'm more interested on how deal with the conflict.
If I just remove window_set_caption() from screen_refresh() and instead call it once on room change, then the conflict will be solved and it will work with older examples. I find that a good solution. The only issue will be that setting room_caption in code will not change the caption and instead you will have to call window_set_caption. I could make room_caption to be reflexive_type, which would make it work like speed, hspeed or vspeed as in changing its value will actually call a function. In this case calling assignment operator on room_caption it will call window_set_caption. Now it would be totally backwards compatible and yet without conflicts.
Only multifunction_variant.cpp has a very large "there be dragons" warning in using multifunction_variant, but I guess in this case it wouldn't apply to purely reflexive_type? Josh can weight in here, as I think it is his warning.

**Comment by RobertBColton** [comment]
@TheExDeus I agree because at first I was all like, what? But anyway, I thought one of the drag and drop actions for score or lives set's the window caption? If so, it probably needs to do that through room_caption.

**Comment by TheExDeus** [comment]
I don't think that action actually does anything. It sets some variables, but they are never used.

**Comment by RobertBColton** [comment]
@TheExDeus look under the "score" tab in LGM's drag and drop. It has "Score Caption" to set the window title to it. I don't think we should break that, I think it's best we just leave it alone. Like I said, ENIGMA 2.0 is a better idea.

**Comment by TheExDeus** [comment]
Yeah and look at the code: https://github.com/enigma-dev/enigma-dev/blob/master/ENIGMAsystem/SHELL/Universal_System/actions.h#L108

Also, none of the things I have done in the past year have made ENIGMA more compatible with GM, so I'm personally already working on ENIGMA 2.0 this whole time. I haven't removed much code (to remove stuff we don't need, like these useless actions), but ENIGMA is totally incompatible with GM already.

**Comment by rpjohnst** [comment]
I think what Robert means by "ENIGMA 2.0" is not so much "add individual tweaks without necessarily any regard for GM compatibility" but "burn it to the ground without any assumptions coming from GM compatibility."

**Comment by RobertBColton** [comment]
@TheExDeus I got the lighter fluid already

**Comment by TheExDeus** [comment]
Yeah, but the fact that he didn't want me to change this here and basically "save it for ENIGMA 2.0" implies that we are trying to make "one last GM compatible ENIGMA" before making a fork. I don't have such an intention, because we will not maintain ENIGMA 1.0. So I say we just keep moving forward deleting and refactoring everything and forget GM existed right now in master.

**Comment by RobertBColton** [comment]
To tell you what bugs me is that there is occasionally a user that pops up randomly and likes to play with ENIGMA for a bit. I have no intentions of making LGM an ENIGMA only IDE, I'm patching some of the last bugs I can without affecting GM compatibility. At that point I recommend the project just be left alone and forked to an ENIGMA IDE or one started from scratch.

To tell you some reasons I hate ENIGMA:
* I don't want its language, I don't want GML, I don't care if it's compiled. I want a language defined by standards that's friendly to novice users.
* I don't want its compatibility problems.
* I don't want its drag and drop, which I find counter-intuitive to teaching computer programming.
* And best of all, I don't want Swing.

**Comment by TheExDeus** [comment]
I agree on all points. But where does it leave ENIGMA? I know you can make a bugfixed LGM and then move on ENIGMA IDE, but do we make a GM compatible ENIGMA release that we don't ever touch? I don't think it is possible. I could merge the stuff I have done now, let people test it, fix bugs for a while and then make it the last version of GM compatible ENIGMA (just Git fork as ENIGMA compatible) and make the main repo new ENIGMA.

**Comment by RobertBColton** [comment]
That's basically what I think sounds like the best idea. That way it's here if people want it for anything, other people can come along and pick it up and do stuff with it. It can also serve as a good frame of reference. For the next version, it's really better we just start from scratch. And we're already going over some idea's in IRC with entity-component. Josh is basically on board with this FYI, if you haven't picked up on it he really gets sick thinking of the old compiler mess because in his opinion he didn't even design it properly (think Clang vs monolithic GCC). We've all been having this discussion.

And I'm most concerned about making a tool that's user friendly @TheExDeus. The most important thing I want to emphasize is user friendliness. I really like how GM made it easier not just for novices but also advanced programmers to make a game. Nobody gives a shit these days if you use GM or not, just that your game is fun. I want to look at taking these advanced concepts like shaders and breaking them down into simple editors that are not just functional and powerful but elegant and still teach novices the basics of how a shader works.

**Comment by adambadawy** [comment]
@RobertBColton I know this isn't contributing to the dialogue, but can I just say "amen" to everything you're saying? :+1:
