### ISSUE TITLE
Linux games crash at random

### ISSUE THREAD

**Issue by time-killer-games** [enigma-dev/enigma-dev#1741]
even with an empty 1 room project. eveything I make on Linux crashes. sometimes it works, other runs it dumps out at random times near or at startup. Might be an XLib-exclusive issue. I'm too lazy to confirm this with SDL rn. Also, Ubuntu doesn't show the usual "This application quit unexpectedly" error that crashes usually have. It just looks like the game is closing normally, but I know it isn't, because game_end isn't being called, and I'm not doing anything to close the game when this happens.

**Comment by RobertBColton** [comment]
See if it occurs in debug mode, if so, run gdb in debug mode, otherwise attempt to run gdb on the run mode executable.

**Comment by time-killer-games** [comment]
would it be possible to do it on a compile mode exe since in theory that isn't much different from run mode?

**Comment by time-killer-games** [comment]
otherwise, I'll do it with debug mode.

**Comment by time-killer-games** [comment]
Here's what it gave me doing compile mode after the game froze:

https://pastebin.com/kYz7ewun

**Comment by fundies** [comment]
you wanna type "bt" into gdb after it crashes in debug mode

**Comment by time-killer-games** [comment]
lol whoops idk how i missed that it was the first thing i saw when the page loaded after you told me that. Will edit this post with the results it gives.

**Comment by RobertBColton** [comment]
Where is the engine crashing Sam? Why don't you tell me based on that stack trace instead of me giving you the answer. Remember the point is that you learn to read a stack trace.

**Comment by fundies** [comment]
I'll give you hint. It's @RobertBColton's fault as per usual

**Comment by time-killer-games** [comment]
@RobertBColton I already read last night the files and lines it erorred at, Robert. Excuse me for wanting to go to bed. I have no reason to spoon feed you that information when you should be able to read the stack trace yourself.

**Comment by RobertBColton** [comment]
It seems with high probability the problem is caused by your Nouveau driver, please try updating it.

**Comment by time-killer-games** [comment]
I couldn't figure out how to update the driver so alternatively if this helps at all I switched to an NVIDIA driver. It doesn't seem to crash at total random anymore. But just like the other driver, it consistently crashes when the full screen window loses focus via Alt+Tab.

**Comment by RobertBColton** [comment]
Try OpenGL3 in debug mode and look for anything printed in the console, since GL3 debug mode enables OpenGL debug mode and prints warnings and errors using a callback TheExDeus wrote. Double check that the game setting for vertical synchronization is off/disabled.

Crash is here, so either your driver hates screen refresh or the engine is calling it wrong:
<https://github.com/enigma-dev/enigma-dev/blob/eabb1b474d5abf7e2d58ae3eccf4ba875208a9c9/ENIGMAsystem/SHELL/Bridges/xlib-OpenGL/graphics_bridge.cpp#L111>

Another workaround is for you to use SDL which uses its own swap control.

**Comment by RobertBColton** [comment]
To reiterate, the realm of possibilities includes:
1) There's a bug in your installed MESA libraries
2) There's stack corruption somewhere else in the engine overwriting the variables passed (unlikely as you can reproduce it 100% of the time)

GMS would not have this problem since its installer likely includes binaries which are statically linked to versions of the MESA library different from the bugged one you have installed.

**Comment by time-killer-games** [comment]
Here's the installer script GMStudio 1.4 uses:
```
#!/bin/bash
sudo apt-get install libopenal1 libopenal1:i386 lib32z1 libbz2-1.0:i386 libstdc++6:i386 libxxf86vm1 libssl1.0.0:i386 libglu1-mesa:i386 libxrandr-dev libxrandr2:i386 zip unzip
```

Here's the installer script GMStudio 2.x uses:
```
#!/bin/bash
sudo apt-get install libopenal1 lib32z1 libbz2-1.0 libstdc++6 libxxf86vm1 libssl1.0.0 libglu1-mesa libxrandr-dev libxrandr2 zip unzip
```

Notice both of these contain libglu1-mesa which implies that is NOT statically linked. Sure, when ENIGMA is known to be multitudes buggier than GMStudio, it makes sense to blame the libraries I have installed via sudo apt-get and NOT engima itself. ESPECIALLY since the bug does not happen in GameMaker, provided both software rely on the same exact dependency that you say is broken.

Yes, that makes a TON of sense!

**Comment by RobertBColton** [comment]
GMS is not known to conform to all of the established conventions of any given platform. The fact that did here is exceptional. I also expected them to be linking ANGLE which is usually statically linked to libglu1-mesa.

Regardless, try disabling vertical synchronization. When the game starts we check what swap control extension paths are available. Sounds like we're selecting a bugged one. If there's no crash with vertical synchronization disabled, then we know that's the cause.

**Comment by RobertBColton** [comment]
Also, another possibility I just noticed now is that GMS installed the 32 bit libglu1-mesa because it can't built 64 bit games. It may have corrupted the 64 bit one ENIGMA was using, since Ubuntu/Debian isn't so nice about install 32 _and_ 64 bit dependencies simultaneously.
https://askubuntu.com/questions/695604/libglu1-mesa-dev-how-to-keep-both-i386-and-amd64-packages

**Comment by time-killer-games** [comment]
GMS 2.x builds 64-bit linux games. 1.4 did 32-bit.

**Comment by RobertBColton** [comment]
I spoke hastily, I meant to say GMSv1.4 can't build 64 bit games. What date did you install the two GMS versions on the same machine as ENIGMA? And to clarify, what is the order all 3 were installed?

Here's something to try. Try creating an exe of a simple 1 room game in GMSv1.4 and GMS2 on the desktop area. See if `libGL.so` is copied somewhere next to the executable.

**Comment by RobertBColton** [comment]
Correction again, `libglu1-mesa` is not the same as `libglu1-mesa-dev`. I believe ENIGMA requires the latter while GMS requires the former from you install script paste. I am not sure if these two dependencies are mutually exclusive. In other words, you may have to remove the GMS one, install the ENIGMA one, to use ENIGMA. And do the converse when you want to use GMS.

**Comment by time-killer-games** [comment]
I have a feeling I permanently fucked up my Kubuntu installation. I'm tempted to just reinstall the distro. I'm having a hard time believing I'm going to be able to fix this otherwise.

**Comment by time-killer-games** [comment]
Well, I reinstalled Kubuntu from the disk image, again, and it still seems messed up in all the same ways. I didn't install GMStudio depends this time, only the x64 ENIGMA depends, and the issue persists. In any case, I'm hoping the reinstall fixed the missing SO file issue. Trying VSync off again.

**Comment by RobertBColton** [comment]
Try OpenGL3 with SDL. I forgot we don't create a core context with GLX, but with SDL we do. That may by chance work or it may not.

**Comment by time-killer-games** [comment]
Using SDL with OpenGL3 is still giving me a blank screen. That said, I'll try building the game with SDL and see if it still crashes using plain old OpenGL1.

**Comment by time-killer-games** [comment]
@RobertBColton I reinstalled Kubunti and the crashes no longer happen now. Weird thing is, last time I tried that it didn't solve or change anything but this time it did. I just wanted to let you know it was probably an issue with Kubuntu, not ENIGMA, after all, just like you originally suspected.

**Comment by RobertBColton** [comment]
Sure, closing is the correct thing to do now. However, since you just did that with me having merged fixes for crashes on Windows, it could have been that which fixed it too.
https://github.com/enigma-dev/enigma-dev/commit/1ab91aefefe8fd7019ffbab876448b7bf65463b0
https://github.com/enigma-dev/enigma-dev/commit/759315007afebba599e14635dd12f51669cf97af

**Comment by RobertBColton** [comment]
I'll also add here that napkin basically had the same problems in #1449 not too long ago and it was fixed the same way. Go figure.
