### ISSUE TITLE
Logs Contain ANSI Escapes

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#1833]
So, the LGM output being full of junk ANSI symbols right now is one thing, we have a plan to deal with it. Having the ANSI escapes also in the redirected log files is just unacceptable. I went in there to read the logs because I couldn't read them in LGM. Logs should never contain ANSI escapes because text editors usually never handle them.

However, tools like VS Code do have extensions now that allow you to see log files with ANSI escapes. Maybe we should make this a separate setting for the log files or just output the log files twice, one plain text, one with ANSI escapes.
https://marketplace.visualstudio.com/items?itemName=emilast.LogFileHighlighter

**Comment by fundies** [comment]
There's no good way to remove them afaik. This is because you can't really remove them while you're writting. You can strip them after like I do when pastebining them but theres no guarantee we get to that step without a crash. I've created ./shared_logs.sh so ppl can just run that and send us links to the 3 logs that are stripped of ansi.

**Comment by RobertBColton** [comment]
Closing for now since you did your due diligence, there's nothing more for ENIGMA to do or change. Perhaps later we can look at more UI settings for stuff.
