### ISSUE TITLE
Steam Workshop SDK/Third Party Integration

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#1881]
ENIGMA currently lacks third party integration with various digital distribution platforms such as Steam, Xbox, or Origin. First class support for these services would make it easier for Indie developers to publish ENIGMA created games. Developers would like for it to be easier to monetize their games and enable them to release bigger and better updates to their users. Compatibility with existing GameMaker API would be a secondary priority, as [GameMaker only supports Steam](https://marketplace.yoyogames.com/assets/10709/steamworks-ext) officially.

**Impact**
Integration should allow game developers to improve audience capture and have better data science-backed insights.

**Milestones**

1) Project begins with creation of a new Steam API extension to ENIGMA's Universal System. This is where the engine functions can be implemented, while still allowing developers to disable the API if they don't need it in their game.
** Open question: Build system will need to be investigated; how compatible is Steam SDK with MSYS2/pacman? (1 week)
2) Contributor can progress with basic abstractions for user accounts and log in capabilities. (2-3 weeks)
3) The engine functionality would need to be followed by changes to the protocol buffer format for game settings. All of the game settings, and potentially more for ENIGMA-specific features, will need to be added. (2 weeks)
4) User friendlist, game invites, and stat tracking can optionally extend the project at the contributor's request. (3-4 weeks)

**Mentors:**  Robert, Josh
**Difficulty:**  Medium
**Expected size:** 300h - 350h
**Skills required:**  C++ fundamentals, Web/HTTP API, JSON
**Skills preferred:**  Knowledge of batch API requests and Steam Workshop profile is ideal.

**Comment by saifkandil** [comment]
Milestones

 1. Project begins with creation of a new Steam API extension to ENIGMA's Universal System. This is where the engine functions can be implemented, while still allowing developers to disable the API if they don't need it in their game.
** Open question: Build system will need to be investigated; how compatible is Steam SDK with MSYS2/pacman? (1 week)
 2. Contributor can start by writing a specific Makefile for the extension for testing the implemented APIs. (1 week)
 3. Contributor can progress with basic APIs like General API as well as Overlay API. (2 weeks).
 4. Contributor can progress with main APIs such as Achievements, Stats, and Cloud APIs. (4-6 weeks).
 5. There are much more APIs that may need to be implemented so it's up to the contributor to specify what are the main APIs and what stretched goal.
 6. Contributor can ask for a stretching period for any latency or in order to implement more APIs.

I think those milestones are more convenient for me. What do you think? @fundies @RobertBColton 

Also, I can't understand what this means ``The engine functionality would need to be followed by changes to the protocol buffer format for game settings. All of the game settings, and potentially more for ENIGMA-specific features, will need to be added. (2 weeks)``, so please can you explain it more?
