### ISSUE TITLE
Windows builds broken

### ISSUE THREAD

**Issue by fundies** [enigma-dev/enigma-dev#1972]
Updates to msys' libffi package appears to have broken building the win32 platform.

pacman -Syu to upgrade msys and do a fresh game build to reproduce

**Comment by RobertBColton** [comment]
Not sure about this one as there is relatively little documentation on the internet about `FFI_STDCALL` and `CC_STDCALL` which somehow seem to be related.
```
[01m[KPlatforms/Win32/WINDOWSexternals.cpp:106:59:[m[K [01;31m[Kerror: [m[K'[01m[KFFI_STDCALL[m[K' was not declared in this scope; did you mean '[01m[KCC_STDCALL[m[K'?
  106 |   status=ffi_prep_cif(&(a->cif), ((calltype==dll_stdcall)?[01;31m[KFFI_STDCALL[m[K:FFI_DEFAULT_ABI), ac, restype, a->arg_type);
      |                                                           [01;31m[K^~~~~~~~~~~[m[K
      |                                                           [32m[KCC_STDCALL[m[K
```

**Comment by RobertBColton** [comment]
Actually, this seems to be normal, the libffi devs must have removed `FFI_STDCALL` from 64 bit Windows builds because it's not appropriate to use that calling convention there. It's also not appropriate to use the `FFI_MS_CDECL` calling convention either. The GML API itself actually needs extended with additional constants for appropriate 64 bit calling conventions. On ENIGMA we just made `dll_cdecl` use the default ABI, which happens to be `FFI_MS_CDECL` on 32 bit.
