### ISSUE TITLE
Room Switching Compatibility

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2048]
So ENIGMA was pretty good on GM8.1 compatibility for a while, until #1968 when tkg disabled centering of the window when switching rooms. GM8.1 used to recenter the window when you switched rooms only if you had moved it. It would also resize the window to the size of the new room. GMSv1.4 removed both of these things, provoking tkg to remove the centering from ENIGMA but not the resizing.

Project Mario actually relied on this during its load and initialization. The game would start in a 100x100 loading room before switching to an 800x600 intro room. Because tkg removed the centering behavior of GM8.1, but not the resizing behavior, this causes the game to end up in the bottom right corner of the screen.

@time-killer-games I don't know why you decided to go half way and only do half of what GMSv1.4 did, but you also should have used the compatibility setting to change this.

Anyway, from testing I can see that GMSv1.4 will now shrink or grow the window on changing rooms.

**Comment by time-killer-games** [comment]
Uhm not make this post die. This is VERY undesirable fucktarded behavior and this is why no game engine on the planet ever did this except ancient versions of GameMaker. @JoshDreamland don't let Robert ruin enigma. Centering the game on room start NO competent game engine does, even YoYo stopped doing this since GameMaker HTML5 which launch a decade ago.

**Comment by time-killer-games** [comment]
@RobertBColton I'm sorry Robert for my comments. I going to delete what's left from my pr. I don't what's going on with *me* today.
