### ISSUE TITLE
Joystick Events

### ISSUE THREAD

**Issue by RobertBColton** [enigma-dev/enigma-dev#2113]
The ones in the event selector in LGM, they aren't implemented in the engine. Since RGM's new event selector should support more than two joysticks we need to have these events parameterized using the new events.

**Comment by mikeypro83** [comment]
Shouldn't the use of the SDL controller implementation let you drop the joystick stuff (internally) and use the controller implementation for the joystick events, since the joystick is wrapped inside the controller? The entire gamemaker gamepad system is whack already and incorrectly assumes gamepad manufacturers assign button numbers to the same buttons for every gamepad in existence and wont have more than enigma::user_padr number of buttons.
