### ISSUE TITLE
ENIGMA introduces clipping into .ogg audio

### ISSUE THREAD

**Issue by zulc22** [enigma-dev/enigma-dev#2140]
### Describe the bug
ENIGMA introduces clipping into .ogg audio when the file itself has none.

### Steps To Reproduce
1. Compile this example project and run it. 
[enigmabugreport.zip](https://github.com/enigma-dev/enigma-dev/files/5215094/enigmabugreport.zip)

### Expected behavior
The audio is expected to not clip.

**Comment by RobertBColton** [comment]
Ehhh, I saved it out and I think it sounds more like noise than clipping inside the game. It could be the OGG decoder we are linking to OpenAL soft and thus a MinGW bug.

**Comment by RobertBColton** [comment]
Ok, I did some more deep investigating of the issue. I really don't see anything out of place with how we are playing the sounds. I even tried playing around a bit with source properties, to make sure they were the defaults. I tried looking at all the dependencies, and to see if there's any issues reported online against the libs, and only discovered I can still play OGG after removing libogg from the Makefile for some reason. Maybe @fundies or @time-killer-games could shed some light on that for me, but I digress.

The main big piece of information I found here is heavy indication this is a WINE bug. MinGW gets a lot of its headers and stuff from WINE (DirectSound for sure) but I am not certain about OpenAL soft. Regardless, I know GameMaker is using OpenAL and on a similar sounding issue posted against OpenAL soft I noticed a game mentioned called Hyper Light Drifter. That immediately struck me as familiar, because it is actually a GameMaker made game.
https://github.com/kcat/openal-soft/issues/226

The reason this wouldn't repro in GMSv1.4 I presume is because YoYo did something recently with respect to linking OpenAL to avoid MP3 licensing concerns or something to that effect. I'm not entirely sure this is the issue, but it definitely seems to fit the bill, until somebody finds out more about this.

**Comment by JoshDreamland** [comment]
Are you not able to reproduce the problem on your machine, Robert? AFAIK this is a problem with the sample size we're using. I think we're using 8 bit samples for our PCM data, so audio files with high volume are being clipped at 255. I can't imagine that being local to one machine.

**Comment by RobertBColton** [comment]
@JoshDreamland yeah I can, as I said, it's static. But we are using alure to load the sounds (unlike GM) which configures the format for us. I was looking at the docs for OpenAL about how to configure it after the fact though. I'll have to do deeper testing then and try manually loading the audio in ENIGMA.

@zulc22 Could you please also file an issue on OpenAL soft if you know how? If not, could you give me permission to use your ogg file? The reason I ask is because I can't seem to repro it with other OGG files (even higher quality ones that fit Josh's description). If you give me permission, I'm a bit busy, but I can get around to writing a self contained OpenAL soft + Alure example for them which should make it easier for them to help figure it out.

**Comment by zulc22** [comment]
@RobertBColton i did this on arch linux; and yes you have permission from me to use that .ogg file

**Comment by zulc22** [comment]
i think i encoded the ogg with either ffmpeg or fluidsynth. not quite sure. i'm on windows now so i can't do that much testing on the linux side

**Comment by zulc22** [comment]
and i wasn't cross-compiling or anything; this was a native linux compile and run.

**Comment by RobertBColton** [comment]
Oh, that's interesting, I thought you were on Windows. That's weird I get what sounds like noise when the song gets above a certain decibels over on Windows 10. Anyway, thanks, when I can, I'll try to submit the OGG with a working example to OpenAL soft. In the interim, you could also try switching out your pulse audio/driver too.

**Comment by time-killer-games** [comment]
I would love to comment on the ffmpeg issue bringing my opinions to the table but robert disabled me from doing so. I'm sorry he doesn't like me contributing peacefully. I've been much kinder to everyone since my absence from discord, as i continue to improve,the abuse continues on his end

**Comment by JoshDreamland** [comment]
@zulc22 Per discussion in libsndfile/libsndfile#672, your audio file has out-of-range samples and ought to be normalized. You can do this in Audacity (I believe I had you do so earlier). It's probably worth filing a bug against whatever software encoded that file.

One takeaway from the discussion is that the libsndfile behavior is uglier than defined to be for this particular situation, but even the correct behavior is not what you'd want, and you're better off reencoding the file. We could possibly provide calls to normalized audio files automatically; feel free to open a new bug with that request.
