### ISSUE TITLE
instance_*activate and game_restart()

### ISSUE THREAD

**Issue by justinrissler** [enigma-dev/enigma-dev#237]
Place one instance, de-active it and use game_restart(). There will now be two instances, one activated, one de-activated.

**Comment by RobertBColton** [comment]
I checked this off of #427 because I am no longer able to reproduce it on the current master.

I created the following test GMK in GM8:
[instance_deactivated_restart_test.zip](https://github.com/enigma-dev/enigma-dev/files/1998565/instance_deactivated_restart_test.zip)

The number/ord controls for the persistent `object0` are as follows:
1: `instance_deactivate_all(true);`
2: `instance_deactivate_object(object1);`
3: `game_restart()`
4: `room_restart()`

With only one instance of `object1` in the room I can restart the room, restart the game, deactivate the instance as many times as I want and I still only see the message from `object1`'s create event a single time on restart. So the deactivated instance list must be getting cleared now.
