### ISSUE TITLE
Random fails if `ma_scalar` is not double.

### ISSUE THREAD

**Issue by TheExDeus** [enigma-dev/enigma-dev#620]
I used a random function to generate color for curves. It seems that when I use:
color=random_integer(16777216);
I get only variations of dark blue. When I use this:
color=random(0xFFFFFF);
I get variations of yellow.
To make it work I had to use this:
color=random_integer(255) | (random_integer(255) << 8) | (random_integer(255) << 16)
Technically all of the above should of worked. Also this returns only variations of blue:
color=random_integer(c_white);

Example can be seen here:
https://www.dropbox.com/s/2lgj9pyr0cf6cli/curves_example.gmk
Press two times right to go the room where you can draw with the mouse. Left click create a point with random(0xFFFFFF);, while right click creates a point with the 3 times random solution. Previously all of them worked. Maybe this is because of the ma_scalar? But even before it got cast correctly. Maybe it is something to do with the color changes.

**Comment by JoshDreamland** [comment]
Just so Robert remembers what I told him the problem was for the 21st and 22nd times: The values I use to generate random numbers come from the Delphi PRNG. Most are too big to fit in a float, and too small to randomize a quad. That implementation should always just use double, no matter what `ma_scalar` is.
