### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [enigma-dev/enigma-dev#650]
I would like to point out that identifiers like "[`_SETTINGS_H`](https://github.com/enigma-dev/enigma-dev/blob/cfd74c3abe634bcac3c7d5a4ca74378c32ecdc6e/CompilerSource/settings.h#L27)" and "[`enigma_type__var`](https://github.com/enigma-dev/enigma-dev/blob/0433a98e98ca364a7360d5185290d606a238fbe1/CompilerSource/compiler/compile_includes.h#L29)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL32-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by RobertBColton** [comment]
Closing this one as resolved because the reserved identifier violations in the engine were fixed by me in #1174. The JDI ones should be fixed in JDI's repo or in a way that doesn't create additional merge conflicts/ass pain for Josh. If you see anymore in the engine, fix them as you discover them but I'm pretty sure I got all of them.
