### ISSUE TITLE
sound_replace does not work

### ISSUE THREAD

**Issue by SuperRiderTH** [enigma-dev/enigma-dev#686]
I am trying to replace a sound and then play it and when I do it doesn't appear to play anything.
I am doing:

global.musicintro=sound_add(string(global.filePath)+"Blank.ogg",0,0)
global.musicloop=sound_add(string(global.filePath)+"Blank.ogg",0,0)
sound_replace(global.musicintro,string(global.filePath)+global.musicintrofile,0,0)
sound_replace(global.musicloop,string(global.filePath)+global.musicloopfile,0,0)

and when I try to play it nothing happens.

**Comment by RobertBColton** [comment]
Closing this one for a number of reasons, but mainly because I just fixed it in #1219.

1) It wasn't working after you play the sound because the buffer was still attached to a source. That can't happen now because I create a new buffer, and put the old one in a garbage collected list.
2) This should have taken care of most of the memory leaks.
3) `sound_replace` did not previously exist for DirectSound, but now it does.

With the changes I did, it now not only works for me but I can also press enter and replace a sound while playing it by holding the spacebar. Not OpenAL errors, and works in both systems. The only difference now is that OpenAL does not stop a sound from playing when you delete it or replace it, but DirectSound does (like legacy GM). Because `sound_add` is deprecated, `sound_replace` is obsolete, and `audio_add` was never a thing in GMS, we can define all of them to do whatever we want and I felt this was better and will keep people from making mistakes when deleting sounds/etc.

You should not try updating yet to get these fixes, just be patient. We are still working on a new IDE and I am just fixing bugs as they get in our way developing emake/RadialGM:
https://enigma-dev.org/forums/index.php?topic=2888

Just stay tuned for more updates.
