### ISSUE TITLE
make-directory is not (really) honored cross-platform.

### ISSUE THREAD

**Issue by sorlok** [enigma-dev/enigma-dev#805]
I ran into a peculiar problem when trying to compile the EGM file for Iji (generated in Linux) on Windows. In the EnigmaSettings.ey file, there's this:

```
make-directory: "%HOME%/.enigma/"
```

The problem is that API_Switchboard.h is constructed here, but SHELLmain.cpp tries to #include the API_Switchboard.h defined in "%PROGRAMDATA%/ENIGMA/", which is the default for all projects on Windows. This leads to totally unrelated error messages.

My question is actually: how do you want this fixed? It seems to me that if someone does development on both Windows and Linux, then there is no really good option for "make-directory". However, %HOME% does actually work on Windows, so I can try to make the above example build there ...if that's the right thing to do.

**Comment by fundies** [comment]
I think this is something that should be handled by the yaml the ide send to enigma.

**Comment by RobertBColton** [comment]
It was but we disabled that in #844. Silly me, I totally forgot we disabled it.

Anyway, in CodeBlocks and other IDEs you usually configure where your project output goes. That's what I was trying to base this off of. It would have defaults for each platform, which it still does, and the user could change it, say if they wanted it locally next to the project files like your typical "/bin" folder with GCC.

The thing missing here is technically a global override so that it doesn't have to be configured on a per-project basis, something CodeBlocks also has. Qt for example would save it the same way we had it, but it saves it in a user config file that saves your Qt Creator tabs and everything. You typically delete this kind of file before committing it to Git or moving to another platform.

The easier method for ENIGMA to do is to go back to using the YAML and just create an actual separate make-directory for each platform. That would be make-directory-windows make-directory-linux etc.

The other thing is that GameMaker: Studio/GMX has a setting for this which defaults to %LOCALAPPDATA% on Windows. So maybe we could just implement the global game setting and use that since it has an option separate for each platform in GMS.

![image](https://user-images.githubusercontent.com/3212801/34342731-43f8587a-e987-11e7-8ebd-026035a25e9d.png)

So there's three options here:
1. Add a global override for the make directory. In other words add an ENIGMA preferences panel to accompany the ENIGMA game settings panel in LGM.
2. Add a make directory specific to each platform, not just a platform default.
3. Add the actual game setting for it from GMS and use that. This is basically the same as 2

We should probably do 3 and go with it. I had a problem with adding all of the configuration options from GMS though because I didn't quite know if it made sense to duplicate settings for each platform when it supports multiple configurations and whether or not that's something ENIGMA wants to support.

**Comment by JoshDreamland** [comment]
If this is bothering you, Robert, then by all means add a key to `gcc.ey` and the other compiler descriptor files.

**Comment by RobertBColton** [comment]
@JoshDreamland wouldn't that just replace the "Default-{PlatformName}:" format me and you already came up with?
https://github.com/enigma-dev/enigma-dev/blob/8c8d6878f6cd57746c9894dbd5d4cc7f85536ab8/settings.ey#L49

**Comment by JoshDreamland** [comment]
Yes, it would. I don't mind it being there, either. Is it actually being used?

**Comment by RobertBColton** [comment]
Ok. It was, but I let sorlok disable it in #844. So yeah I did have the syntax for it and everything working. In fact, Default-{PlatformName} will still technically work with the other settings as well. But again, the problem was that he started a project and then moved platforms where "make-directory" became stale and should have been reset to that platform's default. So yeah I am in favor of multiple settings and or using the same exact setting that's in GMS.
