### ISSUE TITLE
Instance Deactivation Bug 1

### ISSUE THREAD

**Issue by polygoned** [enigma-dev/enigma-dev#85]
Reactivating instances after using instance_deactivate_all() crashes enigma.

**Comment by RobertBColton** [comment]
I've checked this off of #427 because I can't reproduce it.

I created the following test GMK in GM8 which works fine on current master:
[instance_deactivate_all_reactivate_test.zip](https://github.com/enigma-dev/enigma-dev/files/1998508/instance_deactivate_all_reactivate_test.zip)

Use spacebar to deactivate all `object1` instances (with `instance_deactivate_all(true)` from object0) and enter to reactivate them. Works fine in ENIGMA, not crash even under gdb.
