### ISSUE TITLE
gamepad_button_check/gamepad_button_check_pressed does not function properly.

### ISSUE THREAD

**Issue by SuperRiderTH** [enigma-dev/enigma-dev#900]
Using gamepad_button_check/_pressed in place of keyboard_check/_pressed does not work as expected.

I am working on a menu, and this causes the menu to move rapidly when the gamepad is pressed. 

`if keyboard_check_pressed(vk_left) or gamepad_button_check_pressed(0, gp_padl) { move left once }`

Keyboard works as expected.

This:

`if keyboard_check(vk_left) 
or gamepad_button_check(0, gp_padl)
    {
        leftTime+=1
    }
`

Does not work as expected when gamepad is pressed. It actually appears to do nothing at all.

**Comment by RobertBColton** [comment]
This issue was because I didn't set up the extension to be able to look at the last state of the gamepad as well as the current state of the gamepad. So pressed was just checking if the button is down and released was just checking if it's not down. To do pressed/released properly you have to look at the current frame and the previous frame's gamepad state. This is resolved in #1452 where I do exactly that.

**Comment by RobertBColton** [comment]
Closing as resolved by #1452.
