### ISSUE TITLE
MP3 not working on Windows cross-compiled from Linux.

### ISSUE THREAD

**Issue by sorlok** [enigma-dev/enigma-dev#909]
Not really sure why, but mp3s have never worked when cross-compiling from Linux to Windows. I am opening this issue partly to ask for ideas, but also to provide a work-around. In Audio_Systems/OpenAL/Makefile, change this:

```
else ifeq ($(PLATFORM), Win32)
    LDLIBS += -lALURE32-static -lOpenAL32 -lvorbisfile -lvorbis -logg -lFLAC -lsndfile -lmodplug -lmpg123 -lole32 -lwinmm
```

...to this:

```
else ifeq ($(PLATFORM), Win32)
    LDLIBS += -lALURE32-static -lOpenAL32 -lvorbisfile -lvorbis -logg -lFLAC -lsndfile -lmodplug -lmpg123 -lole32 -lwinmm
    SOURCES += $(wildcard ../additional/alure/enigma_alure/*.cpp)
    include $(addsuffix /Makefile, ../additional/alure/Codecs)
```

This will force the built-in alure codecs to be used. This only fixes mp3 support (ogg support is still broken) and it's not clear that this is the right solution in general. But it is consistent with the OS-X solution.

**Comment by fundies** [comment]
Codecs should really be an option in the IDE. MP3 has a terrible license so right now it's disabled by default. And we force installation of all other codecs which is also annoying, If @RobertBColton can options for this that'd be big help, Also on linux it tries to use the libraries on your system instead of the ones we bundle for windows users. Perhaps this should also be an option in the IDE? If provided with an easy way to set these it's a simple fix.

**Comment by JoshDreamland** [comment]
Resource loading hooks for extensions would fix the codec issues (see #997). No need to add special code to handle codec installation, that way.

**Comment by RobertBColton** [comment]
I think extensions for the codecs is the way to go, you either want them or you don't.

**Comment by fundies** [comment]
putting this in with #997
