### ISSUE TITLE
Game crashes when fonts are used.

### ISSUE THREAD

**Issue by ghost** [enigma-dev/enigma-dev#945]
So my game suddenly stops responding when I use draw_set_font(FONT). If there are any set on startup then the program stops responding on startup. If I use something like "if(keyboard_check(ord("F"))) then draw_set_font(FONT);" then the game stops responding the moment I press F.

![](https://puu.sh/jFYRG/6e7f1c0c8a.png)

The thing about this is that the game was working fine with fonts yesterday. The compiler and editors throw up no errors as far as I can see when the game is run.

**Comment by TheExDeus** [comment]
This is really weird. Have you tried debug mode? When compiled using that you can also try debugging with a debugger. That is a little more complicated though:
1) Run command line (Start>Run>cmd).
2) Go the folder where the debugged game is located (probably a temp folder).
3) Type "gdb nameofthegame.exe"
4) Run
Wait until it crashes
5) bt
That last command should print where it crashed in source. That will help us fix it. There are A LOT of changes in ENIGMA in the past few months that are not in the master though. It is possible this bug is already fixed, but not has been updated. I really hope I can get the time to upload the newest stuff at some point.

**Comment by JoshDreamland** [comment]
You can also retrieve the debug executable name from the LGM scrollback. Just search for "exe" toward the bottom.

**Comment by rorybg** [comment]
I probably did this wrong but here is what I got:

![](https://puu.sh/jGgjh/632d307b8a.png)

**Comment by JoshDreamland** [comment]
Make sure you chose debug mode from the ENIGMA menu. Or maybe it's the Compile menu now. Otherwise, ENIGMA won't include debugging symbols (which is why only ?? appears in the stack trace).

**Comment by rorybg** [comment]
Oops yeah sorry. I haven't used gdb before today so I'm quite bad at this.

![](https://puu.sh/jGjCV/c180955827.png)

That was run using a .bat script with in it: "gdb.exe C:\Users\lenovo\AppData\Local\Temp\egm593348125372896732.exe"

I hope thats what you need!

**Comment by JoshDreamland** [comment]
The string you're drawing contains characters that the font you're setting doesn't contain. For some reason, this is giving ENIGMA a headache. Can you share the string you're drawing with us? You can fix the problem by adding appropriate glyph ranges to the font that's causing the crash.

**Comment by rorybg** [comment]
The string I am drawing is simply:
        draw_text_ext(vx + 24,vy + 24,"x: " + string(vx) + "#y: " + string(vy) + "#FPS: " + string(fps) + "#V: "+string(abs(((vx/32) * (vy/32))-1))+"#D: "+string(distance_between(mouse_x,mouse_y,0,0)), -1, 264);

Where vx and vy are just view_xview[0] and view_yview[0] and distance_between returns a integer value.

I altered the ranges in the fonts and that has seemed to have fixed it! However I can confirm that enigma didn't inform me of any of problems during compiling or running.

**Comment by TheExDeus** [comment]
Thank you for debugging! I have found the problem and fixed it here: https://github.com/enigma-dev/enigma-dev/commit/17d9273a69c6b46360335aa78e8b6bc62a7791b1 . Now when a character out of range is used it will print a non-line-breaking space. The bug was introduced when Unicode support was added (that is many months ago).
The affected functions were:
string_width_ext
string_width_ext_line
string_width_ext_line_count
draw_text_ext
draw_text_ext_transformed
draw_text_ext_transformed_color
draw_text_ext_color

**Comment by JoshDreamland** [comment]
It might be a nice courtesy to users to bundle in a � with each font for this case, but I'd argue it's not worth the work because that little glyph might be the entire reason a texture page doubles in size. Anyway, thanks for the fix, Harri!

**Comment by RobertBColton** [comment]
hero u rang?

**Comment by TheExDeus** [comment]
I can maybe just print "?" but that could also be confusing. Additional debug message could be added though, like if you do it in Debug Mode an error pops up (as we don't have "warnings" or a "console") that says that an unknown glyph was printed. The whole feedback mechanism needs to be changed though. Like the error window needs to be made different (not use show_error() and instead have a custom one) and smarter errors like if the same error is printed all the time you can hide it. Or maybe when run in Debug Mode some kind of permanent console. cmd shows up even now, but you cannot easily use it with LGM and it doesn't notify that something was written in it.

Anyway, food for thought.

**Comment by JoshDreamland** [comment]
Not to mention that "?" is equally likely to not exist. The best thing to do would be to add an option to the font editor to choose a "missing character" glyph, then modify ENIGMA's Font structure to include a reference to it. A checkbox could then be added to include (and use) the unicode replacement character (�).

However, no one's interested in UI work, and at the point where the font editor gets an overhaul, it's time for LGM to support sprite fonts natively (it's totally stupid that GM never did).

**Comment by RobertBColton** [comment]
Why is this issue still left open?

For the record I want to mention that I tested GMS. It seems that it just pretends like there was no character there.

![gmsfontcharacterundefined](https://cloud.githubusercontent.com/assets/3212801/17440062/f6462026-5af8-11e6-8b68-cf52852d291b.png)

**Comment by RobertBColton** [comment]
FYI you guys, because of us losing commits as I reported in #991 this ticket was actually a duplicate of #756 where I had already fixed the issue once before.
