### ISSUE TITLE
Add support for British spelling of 'color'

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#950]
Things like make_colour_rgb() give an 'Unknown function or script' error because enigma doesn't support the British spelling of certain words.

**Comment by JoshDreamland** [comment]
This has been a question of curiosity on my part for some time. Internationalization is certainly something we're interested in, but that doesn't happen a whole lot in code. When you switch your language settings to Spanish, for example, you won't see `si (existe_instancia(obj_0)) para (ent i = 0; i < 10; ++i) dibuje_circulo(...);`. I was thinking it might be cool if you did, but I'm not sure the practicality of doing so. And we certainly wouldn't offer both at the same time. Adding synonyms for all functions in other dialects seems like a good way to pollute the code completion box.

And, not to appeal to tradition, but American English has always been the precedent for library implementations. There's no `glColour4f`, and there's no `D3DCOLOUR_ARGB`. In general, I'm happy to set precedents, but I'd rather do so with a plan.

**Comment by faissaloo** [comment]
I'm just saying this because GameMaker:Studio does this so it would improve compatibility with code written for GameMaker:Studio.

**Comment by faissaloo** [comment]
Whatever, I found the time and just did it myself, here's the pull request:
https://github.com/enigma-dev/enigma-dev/pull/952

**Comment by TheExDeus** [comment]
GM:S is unbelievably inconsistent under YYG. They added lots of UK English functions, while still adding others with American English. For some time we just followed their insanity, but no longer. We never achieved 100% GM compatibility and no longer strive for it. So we actually removed and renamed their functions just to be more consistent. So I don't think we will merge your changes. Maybe in the GM:S compatibility mode (or an Extension, like the GM5 compatibility extension), but certainly not in the main code.

**Comment by RobertBColton** [comment]
I like Josh's idea, and the translations could also be done through conditional compilation using a macro. That said, the code would become illegible if we start doing it for more than just UK English. What is best is to continue using English internally and somehow change the external linkage. We could probably actually modify GCC with an extension or something to do this. I am thinking like we would use all US English internal and then load the function symbols into the translated variant. It would be the best way to do it I think, I wouldn't want any i18n going directly into the source code. User docs could also be translated by including doxygen comments then in the translated function modules.

**Comment by JoshDreamland** [comment]
What I'm getting at is that when you start leaving spec to add niceties, new problems bubble up. First off, I'm already not a fan of having `draw_set_colour` appear under `draw_set_color` in a code completion box. Our handling of overloads is bad enough. We just don't have good enough function metadata structure in place to have LGM figure out that `draw_set_colour` means the same thing as `draw_set_color`, much less that it should display the former in Britain/Australia and the latter everywhere else. We have other cluttersome synonyms strewn throughout the codebase, too, because of GM (like `arcsin` in addition to `asin`); I'd sooner remove those than add `draw_set_colour`.

But in the bigger picture, what happens if we allow full-scale i18n for code, and users go to share that code? We would need a way to normalize (read: Americanize) the code before distributing it. It would have to be convenient, since it's likely impossible to make seamless. Not to mention that any provision taken would be hard to enforce with the EN_US vs EN_GB crossover; the simple solution to that, of course, still applies to other localizations: allow loading multiple i18n profiles, but have one marked as the primary. That would allow users to selectively enable translations they use, while the primary would be shown in, eg, the code completion box.

I'm not actually proposing any of this be done now, of course. I'm just saying, this is the sort of planning I'd suggest doing before going into this problem, to reduce clutter. Refactors are already painful in ENIGMA; they're sort of inherently painful in C/C++ by virtue of having separate header files for declarations.

Anyway, now that I have that off my chest, I should say this: An extension containing a simple header with a handful of l11n `#define`s could be the simple short-term solution. This way, you have to literally open up your extension settings and ask for the extra clutter. It's a little sloppy, especially for users as I believe there's no global "enabled extensions" profile, but it would accomplish the desired effect in the meantime. I'll say this as well: you could totally generate the header in question with a quick regexp over ENIGMA's function name dump.

**Comment by fundies** [comment]
If GM supports it i think we should add the define macros. There's really no harm / effort in it. No need support other languages though imo....

**Comment by SuperRiderTH** [comment]
Just my two cents here, but GM:S _only_ shows the UK spellings of the functions in the editor, and just happens to support the US spelling. Thus, when I work in Studio I usually use the UK spelling. This caused me issues when I had to port my work over to ENIGMA for testing.
![image](https://cloud.githubusercontent.com/assets/5368844/18293682/752153f2-7462-11e6-9927-4c6c8aac3149.png)

Also, even if you were to use the US spelling, it does not attempt to help you with the arguments like the UK version. So most people who work with GM:S are probably used to using the UK functions.
![image](https://cloud.githubusercontent.com/assets/5368844/18293747/cdd9c18c-7462-11e6-9b5d-357ec66570b6.png)
![image](https://cloud.githubusercontent.com/assets/5368844/18293752/db2e1c34-7462-11e6-93ea-4d4025a308cd.png)

**Comment by RobertBColton** [comment]
While I see SuperRider's point, that would actually be considered a bug in GMS. If they are supporting the US spelling of the functions then they should fix their code completion box. I also tested this myself and it does indeed happen with other color functions as well and moving the cursor position doesn't fix it.

**Comment by JoshDreamland** [comment]
I believe ENIGMA would have a similar problem, as LGM's code completion is not aware of macros. That's what I was talking about when I said we don't have good enough function metadata structure in place for this.

I get that you're trying to do a bug scrub, Robert; why not take this issue and the other compile/parse issues and compile them on the Wiki page about it, or into one big "compiler wish list" bug. If you do so, I recommend including the bug numbers so we don't lose track (and can find duplicates easily).

**Comment by RobertBColton** [comment]
For now I am going to go and put it in #81 as I think I deleted all those old lists from the WIki.
