### ISSUE TITLE
draw_sprite_* functions do not obey draw_set_alpha()

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#967]
They do in GMS, it probably just multiplies the set alpha and the alpha specified by image_alpha or the relevant argument in the sprite. draw_set_alpha() does work correctly with the drawing of normal shapes.

**Comment by RobertBColton** [comment]
This problem was introduced by polygonz when he added color and alpha parameters to all drawing functions in https://github.com/enigma-dev/enigma-dev/commit/d7091e706f16f82e72e38f44c74c723e5d37a17e

We can see the problem on each line in the general headers.
https://github.com/enigma-dev/enigma-dev/blob/d7091e706f16f82e72e38f44c74c723e5d37a17e/ENIGMAsystem/SHELL/Graphics_Systems/General/GSsprite.h#L27
```c++
void draw_sprite(int spr, int subimg, gs_scalar x, gs_scalar y, int color = 16777215, gs_scalar alpha = 1);
```
It should actually be this:
```c++
void draw_sprite(int spr, int subimg, gs_scalar x, gs_scalar y, int color = draw_get_color(), gs_scalar alpha = draw_get_alpha());
```

Now it's clear the reason why he made this change, was so you can explicitly specify a different color and alpha if you choose to, nothing wrong with that, but he just set the defaults incorrectly.
