### ISSUE TITLE
Can't compare instance_id with variable

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#975]
I tried to do `if inst!=instance_id` and got this error (I also get similar errors with just a different operation if I try to use one):
```
idate: bool var::operator!=(int) const
   types_extrapolate_alldec(bool operator!=)
                                 ^
Universal_System/var_te.h:41:2: note: in definition of macro ‘types_extrapolate_real_p’
  prefix (int x)       EVCONST suffix\
  ^
Universal_System/var4.h:259:3: note: in expansion of macro ‘types_extrapolate_alldec’
   types_extrapolate_alldec(bool operator!=)
   ^
Universal_System/var4.h:259:33: note:   no known conversion for argument 1 from ‘std::deque<int>’ to ‘int’
   types_extrapolate_alldec(bool operator!=)
                                 ^
```
**NOTE:** (long, redundant, and verbose compile output removed by @RobertBColton to improve readability)

**Comment by RobertBColton** [comment]
You aren't supposed to use instance_id like that.

https://docs.yoyogames.com/source/dadiospice/002_reference/objects%20and%20instances/instances/instance_id.html

It's an array, or in ENIGMA's case a double ended queue. So this is not an issue and can be closed.

**Comment by faissaloo** [comment]
Ah I see, my mistake, I'll close this now.

**Comment by RobertBColton** [comment]
Hey while I'm at it I want to go ahead and mention this other thing I found testing GMS. Besides adding unnecessary semicolons, they made a similar mistake as you did here but with view_enabled.

If you download the completed surfaces demo and open it in GMS you can find:
```gml
if !view_enabled[1] || view_current = 1
{
draw_set_blend_mode(bm_add);
draw_sprite_ext(sprite_index,image_index,x,y,image_xscale,1,dir,c_yellow,alpha);
draw_set_blend_mode(bm_normal);
}
```
In the draw event of obj_Player_Bullet. The mistake they made was also that view_enabled is not an array, according to their docs and also the GM 5 manual.
https://docs.yoyogames.com/source/dadiospice/002_reference/windows%20and%20views/views/view_enabled.html

They apparently thought they fixed this back in 2015 but they did not because I still find it in the latest version.
http://bugs.yoyogames.com/view.php?id=10840

So keep this in mind and remember to check the docs first. If anyone else makes this mistake (I think I have too) remind them of this ticket and that it is not a bug in ENIGMA.
