### ISSUE TITLE
instance_number() and instance_find() don't handle the all constant correctly

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#976]
I'm using this code in a draw event and laid out a few objects around the screen.
```
var i;
for (i=0;i<instance_number(all);i++)
{
    var inst;
    inst=instance_find(all,i)
    draw_text(inst.x,inst.y,string(i))
}
```  
On GM: 
![GM](https://i.sli.mg/IUy6TW.png)  
On ENIGMA:  
![ENIGMA](https://i.sli.mg/ZRizj9.png)  
ENIGMA gets data from garbage because all is a negative value and it results in instance_number() giving a massive number and instance_find() giving an invalid id which in the end results in inst.y and inst.x being extremely large. I have tested instance_find() by itself with a number given as the second argument and the issue with it is still there.

**Comment by JoshDreamland** [comment]
If those functions are coded properly, this problem is much more widespread. My understanding of the state of the system (that is, the state of the system, as I left it) is that all of these functions use `fetch_inst_iter_by_int` to retrieve an iterator over instances to operate on. This being broken would then imply that `fetch_inst_iter_by_int` doesn't handle `all` properly. Looking at both implementations, everything is correct.

The actual problem is in `instance_number`, which just does a lookup of the object ID and returns the size of that list. It needs modified to handle those four constants.

**Comment by JoshDreamland** [comment]
Please verify the fix in that pull request.
