### ISSUE TITLE
GTK stuff is improperly implemented.

### ISSUE THREAD

**Issue by faissaloo** [enigma-dev/enigma-dev#982]
http://enigma-dev.org/forums/index.php?topic=2694  
After using a workaround to get GTK+ stuff to actually compile (because #676), apparently the whole thing is non-functional.

**Comment by RobertBColton** [comment]
Sadly this is likely our fault and GTK teams fault. Ask @JoshDreamland how much they like to break GTK.

Even Oracle is going through it right now to fix GTK:
http://www.infoworld.com/article/3035505/java/java-9-to-address-gtk-gui-pains-on-linux.html

I discovered a while back myself that none of the GTK stuff works properly.

**Comment by JoshDreamland** [comment]
I'm not sure what to do with a big, nebulous bug like this. It's been a long time since I've done anything in ENIGMA, and much longer with GTK. I'm sure the code's all miserably outdated (it was written for GTK2), but the way I used to code, it's likely there's just some call that needs made before any of the functions can be used (especially given how GTK works).

**Comment by fundies** [comment]
Seems to work for me. You need to add a void show_info(...) function. Then it will compile. However it appears that your gtk stuff was never updated when we started using a name space. Functions just need to be scoped under enigma_user. I'd do it myself but I can't tell whats what's a gm function and what's internal in @JoshDreamland ''s code.   It's really a big mess... but it should work

**Comment by fundies** [comment]
Closing as gtk was fixed with the travis commit.

**Comment by RobertBColton** [comment]
Anybody interested in further improving the system can post a detailed plan of attack or send PR.
